language: node_js
node_js:
    - 8

install:
    - yarn install

script:
    - yarn test
after_success:
    - yarn test:travis
    - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
